name: Deploy Worker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Deploy Worker
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            DATABASE_URL
            TELEGRAM_API_URL
            CHAT_ID
            SECURITY_TOKEN
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TELEGRAM_API_URL: ${{ secrets.TELEGRAM_API_URL }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SECURITY_TOKEN: ${{ secrets.SECURITY_TOKEN }}
      - name: Set Telegram Webhook
        run: |
          curl -X POST ${{ secrets.TELEGRAM_API_URL }}/setWebhook \
           -H "Content-Type: application/json" \
           -d '{"url": "${{ steps.deploy.outputs.deployment-url }}", "secret_token": "${{ secrets.SECURITY_TOKEN }}"}'
